on:
  workflow_call:
    inputs:
      github-env:
        description: 'The Github environment to use for this QWEloy'
        required: true
        type: string
      environment:
        description: 'The environment to be created'
        required: true
        type: string
      working-directory:
        description: 'The working directory of Terraform project'
        required: true
        type: string
      vars-path:
        description: 'The path of Terraform var file, relative to working-directory'
        required: true
        type: string
      runner-label:
        description: 'The label of the runner, only supports one at this moment'
        required: false
        default: ubuntu-latest
        type: string
      tfvars:
        description: 'TF variables'
        required: false
        type: string
      
name: PE Deploy
jobs:
  plan:
    uses: ./.github/workflows/terraform-plan-gcp.yaml
    with:
      github-env: ${{ inputs.github-env }}
      environment: ${{ inputs.environment }}
      working-directory: ${{ inputs.working-directory }}
      vars-path: ${{ inputs.vars-path }}
      runner-label: ${{ inputs.runner-label }}
      tfplan-name: plan-${{ inputs.environment }}.out
      artifact-name: artifact-${{ inputs.environment }}
      #tfvars: ${{ inputs.tfvars }}
    secrets: inherit

  apply:
    if: github.ref_name == 'main'
    needs: plan
    uses: ./.github/workflows/terraform-apply-gcp.yaml
    with:
      github-env: ${{ inputs.github-env }}
      working-directory: ${{ inputs.working-directory }}
      runner-label: ${{ inputs.runner-label }}
      tfplan-name: plan-${{ inputs.environment }}.out
      artifact-name: artifact-${{ inputs.environment }}
      #tfvars: ${{ inputs.tfvars }}
    secrets: inherit